version: '3.5'
services:
    # SYNC [200902082800]
    xmongodb:
        container_name: 'ucs_db'
        image: 'mongo:4.0'
        ports:
            - '22081:27017'
        restart: always
        environment:
            - MONGODB_DATABASE="test"
        volumes:
            - './packages/api/mongodb:/data/db'

    xapi:
        container_name: "ucs_server"
        build: ./packages/api
        ports:
            - "22083:22083"
        depends_on:
            - xmongodb
        volumes:
            - './packages/api/src:/usr/src/app/src'
